# -*- coding: utf-8 -*-
"""globalai_6-7.soru.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MzgqEH4GxtvwY1yLXR9hIB4-lzBuS_Ul

#GLOBAL AI HUB PROJE 2

##Kütüphaneler
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""##Dosya Okuma"""

data = pd.read_csv("NetflixOriginals.csv",encoding="ISO-8859-1")

data.head()

"""##Başlık ve Skora Göre Gruplama"""

sub = data.groupby(['Title'])[['IMDB Score']].max()

"""## En Yüksek Skora Sahip İlk 10 Filmi Gösterme"""

best_10_scores = sub.nlargest(10,'IMDB Score')
best_10_scores

"""## IMDB puanı ile 'Runtime' arasındaki İlişki"""

data.corr()
#korelasyon değerinin negatif çıkması iki değişkenin arasında ters yönde bir ilişki olduğunu gösterir.
#0.30-0.70 arası çıkan korelasyona sahip ise orta düzeyde ilişkileri vardır diyebiliriz.

#Heatmap ile de görselleştiriyoruz.
plt.figure(figsize=(10,10))
sns.heatmap(data.corr(),annot = True, cmap = 'Purples');
plt.title("Correlation Between Features")